
"""
DEFRAG KNOWLEDGE BASE
Source Material & Architectural Explanations

This module serves as the 'Single Source of Truth' for the educational tooltips
and deep-dive explainers requested by the user.

Philosophical Framework:
1. Bressloff-Cowan (Mathematical Neuroscience): Form constants.
2. C.G. Jung (Depth Psychology): Archetypes and Individuation.
3. Ra Uru Hu (Human Design): Mechanical differentiation.
"""

TOPICS = {
    "FORM_CONSTANTS": {
        "title": "Bressloff-Cowan Form Constants",
        "short_desc": "Geometric hallucinations generated by V1 visual cortex architecture.",
        "deep_dive": """
        In 2001, Paul Bressloff and Jack Cowan published 'What Geometric Hallucinations Tell Us about the Visual Cortex'.
        They engaged in a symmetry analysis of the primary visual cortex (V1) and determined that the physical architecture
        of our neural wiring naturally generates specific geometric patterns (Form Constants) when excited or destabilized.

        These include:
        - **Tunnels/Funnels**: Representing foveal expansion.
        - **Spirals**: Representing rotational symmetry.
        - **Lattices/Honeycombs**: Representing orthogonal interactions.
        - **Cobwebs**: Representing reticular connection.

        In the DEFRAG system, we treat these not as hallucinations, but as 'Cognitive Topologies'—the base geometry
        of how you organize reality before you impose language upon it.
        """
    },
    "INDIVIDUATION": {
        "title": "The Process of Individuation",
        "short_desc": "Jungian integration of the unconscious into consciousness.",
        "deep_dive": """
        Carl Jung defined Individuation as the process by which a person becomes a psychological 'in-dividual,'
        that is, a separate, indivisible unity or 'whole'. It is not about becoming 'normal' but about becoming
        fully oneself.

        This involves:
        1. **Confronting the Shadow**: Integrating the rejected parts of the self.
        2. **Differentiation**: Separating from the collective psychology (the 'They').
        3. **The Mandala**: The symbol of the Self, representing the total order of the psyche.
        """
    },
    "MECHANICS": {
        "title": "Differentiation Mechanics",
        "short_desc": "The physics of unique cognitive function.",
        "deep_dive": """
        From the lens of Human Design (The Science of Differentiation), we view the body as a quantum vehicle.
        Just as a Ferrari and a Tractor have different mechanics and purposes, human cognitive architectures vary.

        - **Projectors**: Designed to guide energy, not generate it. Success comes from 'Waiting for the Invitation'.
        - **Generators**: Designed to build and envelope. Success comes from 'Waiting to Respond'.
        - **Manifestors**: Designed to initiate. Peace comes from 'Informing'.
        - **Reflectors**: Designed to sample the environment. Clarity comes from the 'Lunar Cycle'.

        We do not fix what isn't broken; we optimize the specific mechanics you were built with.
        """
    },
    "KAIROS": {
        "title": "Kairotic Alignment",
        "short_desc": "Qualitative time (Right Moment) vs. Chronos (Clock Time).",
        "deep_dive": """
        The Greeks had two words for time: Chronos (sequential, quantitative) and Kairos (opportune, qualitative).
        Most productivity systems optimize for Chronos (speed, volume). DEFRAG optimizes for Kairos (timing, resonance).

        A 'Kairotic Alignment' occurs when your internal geometry matches the external field geometry.
        Action taken in this window is frictionless. Action taken outside of it is resistance.
        """
    }
}

def get_topic(key: str):
    return TOPICS.get(key, None)
